### ISSUE TITLE
Instructor Feedback

### ISSUE THREAD

**Issue by droxey** [Keto-Eating/Keto-Recipe-API#35]
Great job, @PhyllisWong and @nsafai! 

Beautiful site!!

You met **95% of the criteria** --- that means you pass this project!! To make it 100%, please submit the following by EOD Tuesday...

- Integrate the PR that contains the nested route (I gave you partial credit for this)
- Fix the bug on sign up (partial credit - can provision users)
- Add more test coverage (partial credit for some tests!)

Thanks,
-d

**Comment by nsafai** [comment]
Hey @droxey thank you 👍 

- [x] We merged the PR that contains the nested route. 

We discussed and decided that this week we're going to focus on our SPD projects and next week we're going to pick back up and tackle the two other issues you brought up:

- [ ] [Fix the bug on sign up (partial credit - can provision users)](https://github.com/Keto-Eating/Keto-Recipe-API/issues/37)
- [ ] [Add more test coverage (partial credit for some tests!)](https://github.com/Keto-Eating/Keto-Recipe-API/issues/38)

I've created new Github Issues to remember, so I'm closing out this ticket.

**Comment by nsafai** [comment]
@droxey just figured out the signup bug and fixed that.
