### ISSUE TITLE
refactor the UI for cart and grocerylist

### ISSUE THREAD

**Issue by PhyllisWong** [Keto-Eating/Keto-Recipe-API#63]
deliverable by Dec 4th

**Comment by nsafai** [comment]
@PhyllisWong can you add some info to this card? Right now it doesn't have enough info to be actionable. If this is now a duplicate of another issue, lets archive it.

**Comment by nsafai** [comment]
actually going to close this ticket for now in an effort to clean up our backlog. if u end up adding more info, feel free to reopen it
